keys:
  - &primary age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
#    - pgp:
#      - *admin_alice
#      age:
#      - *admin_bob